#!/bin/python3

import math
import os
import random
import re
import sys

def diagonalDifference(arr):
    temp = 0
    emp = 0
    for i in range(0,len(arr)):     #from left diagonal
        temp = temp + arr[i][i]
    
    for j in range(0,len(arr)):      #from right diagonal
        emp = emp + arr[j][len(arr)-1-j]
    
    return abs(temp - emp)      # calculate difference

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
