#!/bin/python3

import math
import os
import random
import re
import sys

S = input().strip()
num_errors = 0

# how many letters of the SOS message have been changed by radiation

for i, char in enumerate(S):  
    if i%3 == 1:
        if char != 'O':         #if not O then increase count of error
            num_errors += 1
    else:
        if char != 'S':         #if not S then increase count of error
            num_errors += 1
print(num_errors)


#Input (stdin):- SOSSPSSQSSOR
#Output:- 3
